name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    container: 
      image: "ocaml/opam:alpine"
      options: --user 0
    permissions:
      contents: write

    steps:
      - name: "fetch dependencies"
        run: |
          sudo -u opam opam install -y dune

      - uses: "actions/checkout@v3"

      - name: "build"
        run: |
          chown -R opam .
          sudo -u opam echo "(-cclib -static)" >bin/link_flags
          sudo -u opam bash -c 'eval $(opam config env) && dune build'

      - uses: "actions/upload-artifact@v3"
        with:
          name: binary
          path: _build/default/bin/main.exe
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    # TODO: giving that action `write` on the repo is a bit dodgy!
    permissions:
      contents: write

    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: binary
        # TODO: below release step uses deprecated API `set-output`
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: binary/*
