---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    container: 
      image: "ocaml/opam:alpine"
      options: --user 0

    steps:
      - name: "build"
        run: |
          sudo -u opam install -y dune

      - uses: "actions/checkout@v3"

      - name: "build"
        run: |
          sudo -u opam echo "(-cclib -static)" >bin/link_flags
          sudo -u opam bash -c 'eval $(opam config env) && dune build'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: _build/default/bin/main.exe
