name: "releasetest"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    container: 
      image: "ocaml/opam:alpine"
      options: --user 0

    steps:
      - name: "fetch dependencies"
        run: |
          sudo -u opam opam install -y dune

      - uses: "actions/checkout@v3"

      - name: "build"
        run: |
          chown -R opam .
          sudo -u opam echo "(-cclib -static)" >bin/link_flags
          sudo -u opam bash -c 'eval $(opam config env) && dune build'
          cp _build/default/bin/main.exe _build/default/bin/${{github.workflow}}-${{runner.arch}}

      - uses: "actions/upload-artifact@v3"
        with:
          name: "binary"
          path: "_build/default/bin/${{github.workflow}}-*"
  pre-release:
    name: "Pre Release"
    needs: "build"
    runs-on: "ubuntu-latest"
    # TODO: giving that action `write` on the repo is a bit dodgy!
    permissions:
      contents: "write"

    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: "binary"
        # TODO: below release step uses deprecated API `set-output`
      - name: "debug"
        run: |
          find .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "*"
  release:
    name: "Release"
    needs: "build"
    if: github.ref_type == 'tag'
    runs-on: "ubuntu-latest"
    # TODO: giving that action `write` on the repo is a bit dodgy!
    permissions:
      contents: "write"

    steps:
      - uses: "actions/download-artifact@v3"
        with:
          name: "binary"
        # TODO: below release step uses deprecated API `set-output`
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: "binary/*"
